### ISSUE TITLE
environment and inference

### ISSUE THREAD

**Issue by Kingdroper** [JK-the-Ko/SAR-CAM#2]
Could you please describe the environment configuration and how to inference?

**Comment by JK-the-Ko** [comment]
Hello, I have added the parts that you have requested. If you have any more requests, please feel free to ask.

**Comment by tql12313** [comment]
Could  you please share the trained weight file?

**Comment by JK-the-Ko** [comment]
We do not have the weight file.

**Comment by xavibou** [comment]
Hello, Could you please provide the pre-trained weights for inference without having reproducing the whole training?
Thanks,
Xavi

**Comment by JK-the-Ko** [comment]
I am sorry but we do not have pretrained weight files.
