### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by Eiye1123** [JK-the-Ko/SAR-CAM#3]
Dear author, it's a great honor to see your work, would you mind making your dataset public？

**Comment by JK-the-Ko** [comment]
Hello!
As stated in the paper, all datasets that I have used are opened to public.
Hence, download corresponding data and preprocess them as in the paper.
Thank you.

**Comment by Eiye1123** [comment]
Thank for your reply

**Comment by sun668899** [comment]
> Hello! As stated in the paper, all datasets that I have used are opened to public. Hence, download corresponding data and preprocess them as in the paper. Thank you.
I would like to ask how the data is preprocessed?

**Comment by JK-the-Ko** [comment]
Hello,
How do you mean by preprocessing?
Does it mean the preprocessing such as min-max normalization before fed into the network?

**Comment by sun668899** [comment]
> Dear author, it's a great honor to see your work, would you mind making your dataset public？
Have you obtained the processed data set for training?

**Comment by JK-the-Ko** [comment]
Hello,
the GPU server that I have used is currently broken. Hence, I will not be able to hand you processed dataset.
Thank you.
