### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by sun668899** [JK-the-Ko/SAR-CAM#4]
Could you please send me the adjusted data set? I would be very grateful.

**Comment by JK-the-Ko** [comment]
Hello,
the GPU server that I have used is currently broken. Hence, I will not be able to hand you processed dataset.
Thank you.

**Comment by sun668899** [comment]
Is there any code for processing the dataset?

**Comment by JK-the-Ko** [comment]
I do not have the code. Please use Python and OpenCV to extract patches and use Matlab for adding speckle noise.

**Comment by Polaris119** [comment]
Hello, after I use Matlab to add speckle noise, the training result loss is a negative value. What is the reason?

**Comment by JK-the-Ko** [comment]
As stated in the paper, we have proposed a modified DG loss which has a log scale.
Hence, if the DG becomes less than one, the modified DG loss returns a negative value.
Please refer to the paper for more details.

**Comment by Akhte10** [comment]
C:\ProgramData\Anaconda3\python.exe D:\code\1\SAR-CAM-main\SAR-CAM-main\test.py 
usage: test.py [-h] [--model-name MODEL_NAME] --weights-dir WEIGHTS_DIR
               --clean-image-dir CLEAN_IMAGE_DIR --noisy-image-dir
               NOISY_IMAGE_DIR --save-dir SAVE_DIR [--stack-image]
               [--device DEVICE]
test.py: error: the following arguments are required: --weights-dir, --clean-image-dir, --noisy-image-dir, --save-dir

Process finished with exit code 2

**Comment by JK-the-Ko** [comment]
Hi, you need to specifically add path of the corresponding arguments to run the code.
