### ISSUE TITLE
Issue with weight file parameters

### ISSUE THREAD

**Issue by AllenJHawk** [JK-the-Ko/SAR-CAM#6]
Hello, Author,
I successfully ran python train.py --project PROJECT_NAME --noisy-train-dir NOISY_IMAGE_TRAIN_DIR --clean-train-dir CLEAN_IMAGE_TRAIN_DIR --noisy-valid-dir NOISY_IMAGE_VALID_DIR --clean-valid-dir CLEAN_IMAGE_VALID_DIR and obtained the weight parameters SAR-CAM_best.pth. However, when I ran the second set of code for testing on the test set, I encountered a mismatch between the weights and the architecture when loading the weight parameters. The specific error code is:

RuntimeError: Error(s) in loading state_dict for SAR_CAM: Unexpected key(s) in state_dict: "_conv_in_._conv_.bias", "_conv_out_._conv_.bias", ... "_up_._up_.1._conv_in_._conv_.bias", "_up_._bottleneck_._conv_.bias"...

I am not clear about the specific reason. I hope you can help to clarify. Thank you!

**Comment by JK-the-Ko** [comment]
Did you use multi-gpu enviornment for training and inference?

**Comment by AllenJHawk** [comment]
No, I only have one GPU, RTX3060, for training.

**Comment by AllenJHawk** [comment]
"Hello, after carefully checking the code, I noticed in your test.py file when you create the model instance:
model = Model(
            scale = 2,
            in_channels = 1,
            channels = 128,
            kernel_size = 3,
            stride = 1,
            dilation = 1,
            bias = False
            ).to(device)
model.load_state_dict(torch.load(args.weights_dir))
Shouldn't you change bias = False to bias = True? This is because the weight file generated during training contains bias information. If it's not changed, a mismatch will occur when loading the weights." Hope for your reply, thank you.

**Comment by JK-the-Ko** [comment]
Thank you for finding an error.
I will make a hotfix regrading "test.py".
